apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-services
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/auth-url: "http://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "http://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, Authorization"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: serviceone
            port:
              number: 8090
        path: /v1/service(/|$)(.*)
        pathType: Prefix
  ingressClassName: nginx